#!/usr/bin/env python

import requests
import sys

INPUT_URL_FORMAT = 'https://adventofcode.com/{year}/day/{day}/input'
COOKIE_FILE = 'session-cookie.txt'

PATHS = {
  'input_file': 'inputs/{year}_{day}.txt',
  'source_file': 'src/aoc/puzzle_{year}_{day}.clj'
}

CLJ_TEMPLATE = '''(ns aoc.puzzle-{year}-{day}
  (:require [clojure.string :as string]))

(defn input [] (string/trim (slurp "{input_file}")))
(defn input-lines [] (string/split-lines (input)))

(defn part-one []
  nil)

(defn part-two []
  nil)
'''

if __name__ == '__main__':
  year, day = sys.argv[1:]
  day_no_zeroes = day.replace('0', '')

  args = {'day': day_no_zeroes, 'year': year}
  for key in PATHS:
    args[key] = PATHS[key].format(**args)

  input_url = INPUT_URL_FORMAT.format(**args)

  with open(COOKIE_FILE) as cookie_file:
    cookie = cookie_file.read().strip()
    response = requests.get(input_url, cookies={'session': cookie})
    input_text = response.content

  with open(args['input_file'], 'wb') as input_file:
    input_file.write(input_text)

  with open(args['source_file'], 'w') as source_file:
    source_file.write(CLJ_TEMPLATE.format(**args))
